package st.alr.mqttitude.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CONTACT_LINK.
 */
public class ContactLink {

    private String topic;
    private Long contactId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ContactLink() {
    }

    public ContactLink(String topic) {
        this.topic = topic;
    }

    public ContactLink(String topic, Long contactId) {
        this.topic = topic;
        this.contactId = contactId;
    }

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public Long getContactId() {
        return contactId;
    }

    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
