package st.alr.mqttitude.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table WAYPOINT.
 */
public class Waypoint {

    private Long id;
    private Integer type;
    private String description;
    private Double latitude;
    private Double longitude;
    private String geocoder;
    private Boolean shared;
    private java.util.Date date;
    private Float radius;
    private Integer transitionType;
    private String geofenceId;
    private String topic;
    private Boolean notificationOnEnter;
    private Boolean notificationOnLeave;
    private String notificationTopic;
    private String notificationMessage;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Waypoint() {
    }

    public Waypoint(Long id) {
        this.id = id;
    }

    public Waypoint(Long id, Integer type, String description, Double latitude, Double longitude, String geocoder, Boolean shared, java.util.Date date, Float radius, Integer transitionType, String geofenceId, String topic, Boolean notificationOnEnter, Boolean notificationOnLeave, String notificationTopic, String notificationMessage) {
        this.id = id;
        this.type = type;
        this.description = description;
        this.latitude = latitude;
        this.longitude = longitude;
        this.geocoder = geocoder;
        this.shared = shared;
        this.date = date;
        this.radius = radius;
        this.transitionType = transitionType;
        this.geofenceId = geofenceId;
        this.topic = topic;
        this.notificationOnEnter = notificationOnEnter;
        this.notificationOnLeave = notificationOnLeave;
        this.notificationTopic = notificationTopic;
        this.notificationMessage = notificationMessage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getGeocoder() {
        return geocoder;
    }

    public void setGeocoder(String geocoder) {
        this.geocoder = geocoder;
    }

    public Boolean getShared() {
        return shared;
    }

    public void setShared(Boolean shared) {
        this.shared = shared;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Float getRadius() {
        return radius;
    }

    public void setRadius(Float radius) {
        this.radius = radius;
    }

    public Integer getTransitionType() {
        return transitionType;
    }

    public void setTransitionType(Integer transitionType) {
        this.transitionType = transitionType;
    }

    public String getGeofenceId() {
        return geofenceId;
    }

    public void setGeofenceId(String geofenceId) {
        this.geofenceId = geofenceId;
    }

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public Boolean getNotificationOnEnter() {
        return notificationOnEnter;
    }

    public void setNotificationOnEnter(Boolean notificationOnEnter) {
        this.notificationOnEnter = notificationOnEnter;
    }

    public Boolean getNotificationOnLeave() {
        return notificationOnLeave;
    }

    public void setNotificationOnLeave(Boolean notificationOnLeave) {
        this.notificationOnLeave = notificationOnLeave;
    }

    public String getNotificationTopic() {
        return notificationTopic;
    }

    public void setNotificationTopic(String notificationTopic) {
        this.notificationTopic = notificationTopic;
    }

    public String getNotificationMessage() {
        return notificationMessage;
    }

    public void setNotificationMessage(String notificationMessage) {
        this.notificationMessage = notificationMessage;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
