---
version: "3.0"
volumes:
  recorder-data:
  mosquitto:
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.21-openssl
    ports:
      - 1883:1883
      - 8883:8883
      - 8884:8884
      - 8885:8885
      - 8080:8080
      - 8081:8081
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ${PWD}/mosquitto.password:/mosquitto/config/mosquitto.password:ro
      - ${PWD}/rootCA.pem:/mosquitto/config/rootCA.pem:ro
      - ${PWD}/_wildcard.docker.local-key.pem:/mosquitto/config/key.pem:ro
      - ${PWD}/_wildcard.docker.local.pem:/mosquitto/config/cert.pem:ro
      - ${PWD}/self-signed.crt:/mosquitto/config/self-signed.crt:ro
      - ${PWD}/self-signed.key:/mosquitto/config/self-signed.key:ro
      - mosquitto:/mosquitto/data
  nginx:
    depends_on:
      owntracks-recorder:
        condition: service_started
      mosquitto:
        condition: service_started
    image: nginx
    ports:
      - 8900:8900
      - 8901:8901
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/_wildcard.docker.local-key.pem:/tls/key.pem:ro
      - ${PWD}/_wildcard.docker.local.pem:/tls/cert.pem:ro
      - ${PWD}/rootCA.pem:/tls/ca.crt:ro
  caddy:
    depends_on:
      mosquitto:
        condition: service_started
    image: caddy
    ports:
      - 8910:8910
      - 8911:8911
      - 8912:8912
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${PWD}/_wildcard.docker.local-key.pem:/tls/key.pem:ro
      - ${PWD}/_wildcard.docker.local.pem:/tls/cert.pem:ro
      - ${PWD}/rootCA.pem:/tls/ca.pem:ro
  owntracks-recorder:
    entrypoint: /bin/sh -c "/usr/bin/ocat --load=friends < /friends.txt && /usr/sbin/entrypoint.sh"
    depends_on:
      mosquitto:
        condition: service_started
    image: owntracks/recorder
    ports:
      - 8083:8083
    volumes:
      - recorder-data:/store
      - ${PWD}/friends.txt:/friends.txt:ro
    environment:
      - OTR_HOST=mosquitto
      - OTR_PORT=1883
      - OTR_USER=test
      - OTR_PASS=test
      - LOG_DEBUG=true
  owntracks-frontend:
    depends_on:
      owntracks-recorder:
        condition: service_started
    image: owntracks/frontend
    ports:
      - "8000:80"
    environment:
      - SERVER_HOST=owntracks-recorder
      - SERVER_PORT=8083
