package st.alr.mqttitude.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import st.alr.mqttitude.db.ContactLink;
import st.alr.mqttitude.db.Waypoint;
import st.alr.mqttitude.db.Notification;

import st.alr.mqttitude.db.ContactLinkDao;
import st.alr.mqttitude.db.WaypointDao;
import st.alr.mqttitude.db.NotificationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactLinkDaoConfig;
    private final DaoConfig waypointDaoConfig;
    private final DaoConfig notificationDaoConfig;

    private final ContactLinkDao contactLinkDao;
    private final WaypointDao waypointDao;
    private final NotificationDao notificationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactLinkDaoConfig = daoConfigMap.get(ContactLinkDao.class).clone();
        contactLinkDaoConfig.initIdentityScope(type);

        waypointDaoConfig = daoConfigMap.get(WaypointDao.class).clone();
        waypointDaoConfig.initIdentityScope(type);

        notificationDaoConfig = daoConfigMap.get(NotificationDao.class).clone();
        notificationDaoConfig.initIdentityScope(type);

        contactLinkDao = new ContactLinkDao(contactLinkDaoConfig, this);
        waypointDao = new WaypointDao(waypointDaoConfig, this);
        notificationDao = new NotificationDao(notificationDaoConfig, this);

        registerDao(ContactLink.class, contactLinkDao);
        registerDao(Waypoint.class, waypointDao);
        registerDao(Notification.class, notificationDao);
    }
    
    public void clear() {
        contactLinkDaoConfig.getIdentityScope().clear();
        waypointDaoConfig.getIdentityScope().clear();
        notificationDaoConfig.getIdentityScope().clear();
    }

    public ContactLinkDao getContactLinkDao() {
        return contactLinkDao;
    }

    public WaypointDao getWaypointDao() {
        return waypointDao;
    }

    public NotificationDao getNotificationDao() {
        return notificationDao;
    }

}
