package org.owntracks.android.db;

import org.greenrobot.greendao.annotation.*;
import org.owntracks.android.BR;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.databinding.BaseObservable;
import android.databinding.Bindable;
import android.location.Location;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
// KEEP INCLUDES END
/**
 * Entity mapped to table "WAYPOINT".
 */
@Entity
public class Waypoint extends BaseObservable {

    @Id
    private Long id;

    @NotNull
    private String description;
    private double geofenceLatitude;
    private double geofenceLongitude;
    private Integer geofenceRadius;
    private String geofenceId;
    private String wifiSSID; // unused
    private String beaconUUID;
    private Integer beaconMajor;
    private Integer beaconMinor;
    private Boolean shared; // unused
    private java.util.Date date;
    private Long lastTriggered;
    private int modeId;
    private int type;
    
    @Transient
    private int lastTransition = 0;

    public boolean isDeleted() {
        return isDeleted;
    }

    public void setDeleted(boolean deleted) {
        isDeleted = deleted;
    }

    @Transient
    private boolean isDeleted;

    @Generated(hash = 96494712)
    public Waypoint(Long id, @NotNull String description, double geofenceLatitude, double geofenceLongitude, Integer geofenceRadius, String geofenceId, String wifiSSID, String beaconUUID, Integer beaconMajor, Integer beaconMinor, Boolean shared, java.util.Date date, Long lastTriggered, int modeId,
            int type) {
        this.id = id;
        this.description = description;
        this.geofenceLatitude = geofenceLatitude;
        this.geofenceLongitude = geofenceLongitude;
        this.geofenceRadius = geofenceRadius;
        this.geofenceId = geofenceId;
        this.wifiSSID = wifiSSID;
        this.beaconUUID = beaconUUID;
        this.beaconMajor = beaconMajor;
        this.beaconMinor = beaconMinor;
        this.shared = shared;
        this.date = date;
        this.lastTriggered = lastTriggered;
        this.modeId = modeId;
        this.type = type;
    }

    @Generated(hash = 1578831160)
    public Waypoint() {
    }

    public Waypoint(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Nullable
    @Bindable
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(@NotNull String description) {
        this.description = description;
        this.notifyPropertyChanged(BR.description);

    }

    @Bindable
    public double getGeofenceLatitude() {
        return geofenceLatitude;
    }

    public void setGeofenceLatitude(double geofenceLatitude) {
        if(geofenceLatitude > 90)
            this.geofenceLatitude = 90;
        if(geofenceLatitude < -90)
            this.geofenceLatitude = -90;
        else
            this.geofenceLatitude = geofenceLatitude;
        this.notifyPropertyChanged(BR.geofenceLatitude);

    }

    @Bindable
    public double getGeofenceLongitude() {
        return geofenceLongitude;
    }

    public void setGeofenceLongitude(double geofenceLongitude) {
        if(geofenceLongitude > 180 )
            this.geofenceLongitude = 180 ;
        if(geofenceLongitude < -180 )
            this.geofenceLongitude = -180 ;
        else
            this.geofenceLongitude = geofenceLongitude;
        this.notifyPropertyChanged(BR.geofenceLongitude);

    }

    @Nullable
    @Bindable
    public Integer getGeofenceRadius() {
        return geofenceRadius;
    }

    public void setGeofenceRadius(Integer geofenceRadius) {
        this.geofenceRadius = geofenceRadius;
        this.notifyPropertyChanged(BR.geofenceRadius);
    }

    public String getGeofenceId() {
        return geofenceId;
    }

    public void setGeofenceId(String geofenceId) {
        this.geofenceId = geofenceId;
    }

    public String getWifiSSID() {
        return wifiSSID;
    }

    public void setWifiSSID(String wifiSSID) {
        this.wifiSSID = wifiSSID;
    }

    public String getBeaconUUID() {
        return beaconUUID;
    }

    public void setBeaconUUID(String beaconUUID) {
        this.beaconUUID = beaconUUID;
    }

    @Nullable
    public Integer getBeaconMajor() {
        return beaconMajor;
    }

    public void setBeaconMajor(Integer beaconMajor) {
        this.beaconMajor = beaconMajor;
    }

    @Nullable
    public Integer getBeaconMinor() {
        return beaconMinor;
    }

    public void setBeaconMinor(Integer beaconMinor) {
        this.beaconMinor = beaconMinor;
    }

    public Boolean getShared() {
        return shared;
    }

    public void setShared(Boolean shared) {
        this.shared = shared;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    @Nullable
    public Long getLastTriggered() {
        return lastTriggered;
    }

    public void setLastTriggered(Long lastTriggered) {
        this.lastTriggered = lastTriggered;
    }

    public int getModeId() {
        return modeId;
    }

    public void setModeId(int modeId) {
        this.modeId = modeId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    @NonNull
    public Location getLocation() {
        Location l= new Location("waypoint");
        l.setLatitude(getGeofenceLatitude());
        l.setLongitude(getGeofenceLongitude());
        l.setAccuracy(0);
        return l;
    }

    public void setLastTransition(int status) {
        this.lastTransition = status;
    }

    public int getLastTransition() {
        return this.lastTransition;
    }

    public boolean isUnknown() {
        return this.lastTransition == 0;
    }

    public boolean hasBeacon() {
        return getBeaconUUID() != null;
    }

    public boolean hasGeofence() {
        return (getGeofenceRadius() != null) && (getGeofenceRadius() > 0);
    }
}
