package org.owntracks.android.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
    import android.location.Location;
// KEEP INCLUDES END
/**
 * Entity mapped to table "WAYPOINT".
 */
@Entity
public class Waypoint {

    @Id
    private Long id;

    @NotNull
    private String description;
    private double geofenceLatitude;
    private double geofenceLongitude;
    private Integer geofenceRadius;
    private String geofenceId;
    private String wifiSSID;
    private String beaconUUID;
    private Integer beaconMajor;
    private Integer beaconMinor;
    private Boolean shared;
    private java.util.Date date;
    private Long lastTriggered;
    private int modeId;
    private int type;

    @Generated(hash = 96494712)
    public Waypoint(Long id, @NotNull String description, double geofenceLatitude, double geofenceLongitude, Integer geofenceRadius, String geofenceId, String wifiSSID, String beaconUUID, Integer beaconMajor, Integer beaconMinor, Boolean shared, java.util.Date date, Long lastTriggered, int modeId,
            int type) {
        this.id = id;
        this.description = description;
        this.geofenceLatitude = geofenceLatitude;
        this.geofenceLongitude = geofenceLongitude;
        this.geofenceRadius = geofenceRadius;
        this.geofenceId = geofenceId;
        this.wifiSSID = wifiSSID;
        this.beaconUUID = beaconUUID;
        this.beaconMajor = beaconMajor;
        this.beaconMinor = beaconMinor;
        this.shared = shared;
        this.date = date;
        this.lastTriggered = lastTriggered;
        this.modeId = modeId;
        this.type = type;
    }

    @Generated(hash = 1578831160)
    public Waypoint() {
    }

    public Waypoint(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(@NotNull String description) {
        this.description = description;
    }

    public double getGeofenceLatitude() {
        return geofenceLatitude;
    }

    public void setGeofenceLatitude(double geofenceLatitude) {
        this.geofenceLatitude = geofenceLatitude;
    }

    public double getGeofenceLongitude() {
        return geofenceLongitude;
    }

    public void setGeofenceLongitude(double geofenceLongitude) {
        this.geofenceLongitude = geofenceLongitude;
    }

    public Integer getGeofenceRadius() {
        return geofenceRadius;
    }

    public void setGeofenceRadius(Integer geofenceRadius) {
        this.geofenceRadius = geofenceRadius;
    }

    public String getGeofenceId() {
        return geofenceId;
    }

    public void setGeofenceId(String geofenceId) {
        this.geofenceId = geofenceId;
    }

    public String getWifiSSID() {
        return wifiSSID;
    }

    public void setWifiSSID(String wifiSSID) {
        this.wifiSSID = wifiSSID;
    }

    public String getBeaconUUID() {
        return beaconUUID;
    }

    public void setBeaconUUID(String beaconUUID) {
        this.beaconUUID = beaconUUID;
    }

    public Integer getBeaconMajor() {
        return beaconMajor;
    }

    public void setBeaconMajor(Integer beaconMajor) {
        this.beaconMajor = beaconMajor;
    }

    public Integer getBeaconMinor() {
        return beaconMinor;
    }

    public void setBeaconMinor(Integer beaconMinor) {
        this.beaconMinor = beaconMinor;
    }

    public Boolean getShared() {
        return shared;
    }

    public void setShared(Boolean shared) {
        this.shared = shared;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Long getLastTriggered() {
        return lastTriggered;
    }

    public void setLastTriggered(Long lastTriggered) {
        this.lastTriggered = lastTriggered;
    }

    public int getModeId() {
        return modeId;
    }

    public void setModeId(int modeId) {
        this.modeId = modeId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public Location getLocation() {
        Location l= new Location("waypoint");
        l.setLatitude(getGeofenceLatitude());
        l.setLongitude(getGeofenceLongitude());
        l.setAccuracy(getGeofenceRadius() != null ? getGeofenceRadius() : 0);
        return l;
    }


    public void setDefaults() {
        this.setShared(false);
    }
}
