package org.owntracks.android.ui.preferences.load

import org.owntracks.android.R

/** Maps preference key names to their human-readable string resource IDs. */
val PREFERENCE_KEY_LABELS: Map<String, Int> =
    mapOf(
        "allowConfigurationByURIAndConfigFile" to
            R.string.preferencesAllowConfigurationByURIAndConfigFile,
        "allowIntentControl" to R.string.preferencesAllowIntentControl,
        "autostartOnBoot" to R.string.preferencesAutostart,
        "cleanSession" to R.string.preferencesCleanSessionEnabled,
        "clientId" to R.string.preferencesClientId,
        "cmd" to R.string.preferencesRemoteCommand,
        "connectionTimeoutSeconds" to R.string.preferencesConnectionTimeoutSeconds,
        "debugLog" to R.string.preferencesDebugLog,
        "deviceId" to R.string.preferencesDeviceName,
        "discardNetworkLocationThresholdSeconds" to
            R.string.preferencesDiscardNetworkLocationThresholdSeconds,
        "dontReuseHttpClient" to R.string.preferencesDontReuseHttpClient,
        "enableMapRotation" to R.string.preferencesEnableMapRotation,
        "encryptionKey" to R.string.preferencesEncryptionKey,
        "experimentalFeatures" to R.string.preferencesExperimentalFeatures,
        "extendedData" to R.string.preferencesPubExtendedData,
        "fusedRegionDetection" to R.string.preferencesFusedRegionDetection,
        "host" to R.string.preferencesHost,
        "ignoreInaccurateLocations" to R.string.preferencesIgnoreInaccurateLocations,
        "ignoreStaleLocations" to R.string.preferencesIgnoreStaleLocations,
        "info" to R.string.preferencesInfo,
        "intentAuthKey" to R.string.preferencesIntentAuthKey,
        "keepalive" to R.string.preferencesKeepalive,
        "locatorDisplacement" to R.string.preferencesLocatorDisplacement,
        "locatorInterval" to R.string.preferencesLocatorInterval,
        "locatorPriority" to R.string.preferencesLocatorPriority,
        "mapLayerStyle" to R.string.preferencesMapLayerStyle,
        "mode" to R.string.preferencesProfileId,
        "monitoring" to R.string.preferencesMonitoring,
        "moveModeLocatorInterval" to R.string.preferencesMoveModeLocatorInterval,
        "mqttProtocolLevel" to R.string.preferencesMqttProtocolLevel,
        "notificationEvents" to R.string.preferencesNotificationEvents,
        "notificationGeocoderErrors" to R.string.preferencesNotificationGeocoderErrors,
        "notificationHigherPriority" to R.string.preferencesNotificationHigherPriority,
        "notificationLocation" to R.string.preferencesNotificationLocation,
        "opencageApiKey" to R.string.preferencesOpencageGeocoderApiKey,
        "osmTileScaleFactor" to R.string.preferencesOsmTileScaleFactor,
        "password" to R.string.preferencesBrokerPassword,
        "pegLocatorFastestIntervalToInterval" to
            R.string.preferencesPegLocatorFastestIntervalToInterval,
        "ping" to R.string.preferencesPing,
        "port" to R.string.preferencesPort,
        "pubQos" to R.string.preferencesPubQos,
        "pubRetain" to R.string.preferencesPubRetain,
        "pubTopicBase" to R.string.preferencesPubTopicBase,
        "publishLocationOnConnect" to R.string.preferencesRepublishOnReconnect,
        "remoteConfiguration" to R.string.preferencesRemoteConfiguration,
        "reverseGeocodeProvider" to R.string.preferencesReverseGeocodeProvider,
        "showRegionsOnMap" to R.string.preferencesShowWaypointsOnMap,
        "sub" to R.string.preferencesSub,
        "subQos" to R.string.preferencesSubQos,
        "subTopic" to R.string.preferencesSubTopic,
        "theme" to R.string.preferencesTheme,
        "tid" to R.string.preferencesTrackerId,
        "tls" to R.string.tls,
        "tlsCAInstall" to R.string.preferencesCaCrtInstall,
        "tlsClientCertInstall" to R.string.preferencesClientCrtInstall,
        "tlsClientCrt" to R.string.preferencesClientCrt,
        "url" to R.string.preferencesUrl,
        "username" to R.string.preferencesUsername,
        "ws" to R.string.preferencesWebsocket,
    )
