package org.owntracks.android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CONTACT_LINK.
 */
public class ContactLink {

    private Long id;
    /** Not-null value. */
    private String topic;
    private Long contactId;
    private int modeId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ContactLink() {
    }

    public ContactLink(Long id) {
        this.id = id;
    }

    public ContactLink(Long id, String topic, Long contactId, int modeId) {
        this.id = id;
        this.topic = topic;
        this.contactId = contactId;
        this.modeId = modeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTopic() {
        return topic;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    public Long getContactId() {
        return contactId;
    }

    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }

    public int getModeId() {
        return modeId;
    }

    public void setModeId(int modeId) {
        this.modeId = modeId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
