package org.owntracks.android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
    import org.owntracks.android.model.GeocodableLocation;
// KEEP INCLUDES END
/**
 * Entity mapped to table WAYPOINT.
 */
public class Waypoint {

    private Long id;
    private String description;
    private String geocoder;
    private Double latitude;
    private Double longitude;
    private Integer radius;
    private String ssid;
    private Boolean shared;
    private java.util.Date date;
    private java.util.Date lastTriggered;
    private String geofenceId;
    private int modeId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Waypoint() {
    }

    public Waypoint(Long id) {
        this.id = id;
    }

    public Waypoint(Long id, String description, String geocoder, Double latitude, Double longitude, Integer radius, String ssid, Boolean shared, java.util.Date date, java.util.Date lastTriggered, String geofenceId, int modeId) {
        this.id = id;
        this.description = description;
        this.geocoder = geocoder;
        this.latitude = latitude;
        this.longitude = longitude;
        this.radius = radius;
        this.ssid = ssid;
        this.shared = shared;
        this.date = date;
        this.lastTriggered = lastTriggered;
        this.geofenceId = geofenceId;
        this.modeId = modeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getGeocoder() {
        return geocoder;
    }

    public void setGeocoder(String geocoder) {
        this.geocoder = geocoder;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Integer getRadius() {
        return radius;
    }

    public void setRadius(Integer radius) {
        this.radius = radius;
    }

    public String getSsid() {
        return ssid;
    }

    public void setSsid(String ssid) {
        this.ssid = ssid;
    }

    public Boolean getShared() {
        return shared;
    }

    public void setShared(Boolean shared) {
        this.shared = shared;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public java.util.Date getLastTriggered() {
        return lastTriggered;
    }

    public void setLastTriggered(java.util.Date lastTriggered) {
        this.lastTriggered = lastTriggered;
    }

    public String getGeofenceId() {
        return geofenceId;
    }

    public void setGeofenceId(String geofenceId) {
        this.geofenceId = geofenceId;
    }

    public int getModeId() {
        return modeId;
    }

    public void setModeId(int modeId) {
        this.modeId = modeId;
    }

    // KEEP METHODS - put your custom methods here
    public GeocodableLocation getLocation() {
        GeocodableLocation l= new GeocodableLocation("waypoint");
        l.setGeocoder(getGeocoder());
        l.setLatitude(getLatitude());
        l.setLongitude(getLongitude());
        l.setAccuracy(getRadius() != null ? getRadius() : 0);
        return l;
    }
    // KEEP METHODS END

}
