package org.owntracks.android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
    import android.databinding.BaseObservable;
    import android.location.Location;
// KEEP INCLUDES END
/**
 * Entity mapped to table WAYPOINT.
 */
public class Waypoint extends BaseObservable {

    private Long id;
    private String description;
    private Double geofenceLatitude;
    private Double geofenceLongitude;
    private Integer geofenceRadius;
    private String geofenceId;
    private String wifiSSID;
    private String beaconUUID;
    private String beaconMajor;
    private String beaconMinor;
    private Boolean shared;
    private java.util.Date date;
    private Long lastTriggered;
    private int modeId;
    private int type;

    // KEEP FIELDS - put your custom fields here
    public static final int TYPE_LOCATION = 1;
    public static final int TYPE_BEACON = 2;
    public static final int TYPE_SSID = 4; // not used yet
    // KEEP FIELDS END

    public Waypoint() {
    }

    public Waypoint(Long id) {
        this.id = id;
    }

    public Waypoint(Long id, String description, Double geofenceLatitude, Double geofenceLongitude, Integer geofenceRadius, String geofenceId, String wifiSSID, String beaconUUID, String beaconMajor, String beaconMinor, Boolean shared, java.util.Date date, Long lastTriggered, int modeId, int type) {
        this.id = id;
        this.description = description;
        this.geofenceLatitude = geofenceLatitude;
        this.geofenceLongitude = geofenceLongitude;
        this.geofenceRadius = geofenceRadius;
        this.geofenceId = geofenceId;
        this.wifiSSID = wifiSSID;
        this.beaconUUID = beaconUUID;
        this.beaconMajor = beaconMajor;
        this.beaconMinor = beaconMinor;
        this.shared = shared;
        this.date = date;
        this.lastTriggered = lastTriggered;
        this.modeId = modeId;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getGeofenceLatitude() {
        return geofenceLatitude;
    }

    public void setGeofenceLatitude(Double geofenceLatitude) {
        this.geofenceLatitude = geofenceLatitude;
    }

    public Double getGeofenceLongitude() {
        return geofenceLongitude;
    }

    public void setGeofenceLongitude(Double geofenceLongitude) {
        this.geofenceLongitude = geofenceLongitude;
    }

    public Integer getGeofenceRadius() {
        return geofenceRadius;
    }

    public void setGeofenceRadius(Integer geofenceRadius) {
        this.geofenceRadius = geofenceRadius;
    }

    public String getGeofenceId() {
        return geofenceId;
    }

    public void setGeofenceId(String geofenceId) {
        this.geofenceId = geofenceId;
    }

    public String getWifiSSID() {
        return wifiSSID;
    }

    public void setWifiSSID(String wifiSSID) {
        this.wifiSSID = wifiSSID;
    }

    public String getBeaconUUID() {
        return beaconUUID;
    }

    public void setBeaconUUID(String beaconUUID) {
        this.beaconUUID = beaconUUID;
    }

    public String getBeaconMajor() {
        return beaconMajor;
    }

    public void setBeaconMajor(String beaconMajor) {
        this.beaconMajor = beaconMajor;
    }

    public String getBeaconMinor() {
        return beaconMinor;
    }

    public void setBeaconMinor(String beaconMinor) {
        this.beaconMinor = beaconMinor;
    }

    public Boolean getShared() {
        return shared;
    }

    public void setShared(Boolean shared) {
        this.shared = shared;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Long getLastTriggered() {
        return lastTriggered;
    }

    public void setLastTriggered(Long lastTriggered) {
        this.lastTriggered = lastTriggered;
    }

    public int getModeId() {
        return modeId;
    }

    public void setModeId(int modeId) {
        this.modeId = modeId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    public Location getLocation() {
        Location l= new Location("waypoint");
        l.setLatitude(getGeofenceLatitude());
        l.setLongitude(getGeofenceLongitude());
        l.setAccuracy(getGeofenceRadius() != null ? getGeofenceRadius() : 0);
        return l;
    }
    // KEEP METHODS END

}
