---
# This workflow is triggered on addition of a PR to a merge queue. Essentially we want to run a
# build-test-lint against the merge queue target to make sure the PR applies cleanly on top of
# the target.
name: Merge group checks (build)

"on":
  merge_group:
    types: [checks_requested]

jobs:
  build-test-lint:
    name: Build, Test, and Lint
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/build-test-lint.yaml
    with:
      ref: ${{ github.event.merge_group.head_sha }}
    secrets: inherit
  pr-checkpoint-status:
    name: "PR Checkpoint Status"
    runs-on: ubuntu-latest
    needs: [build-test-lint]
    steps:
      - run: |
          echo "PR Checkpoint Status. Noop"
