---
name: Merge group checks (build)

"on":
  merge_group:
    types: [checks_requested]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: "Debug"
        uses: hmarr/debug-action@v3
  pr-checkpoint-status:
    name: "PR Checkpoint Status"
    runs-on: ubuntu-latest
    needs: [debug]
    steps:
      - run: |
          echo "PR Checkpoint Status. Noop"
