---
name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: "Marking issue with request for more data as stale, due to no updates."
          stale-issue-label: stale
          only-labels: needs-more-info
          debug-only: false
          days-before-close: 30
          days-before-pr-close: -1
          days-before-pr-stale: -1
